Repository rancher/k3k, pull requests merged in 2025-03, with the labels that each got.

#279 Update CRDs documentation
  charts/k3k/crds/k3k.io_clusters.yaml
  charts/k3k/crds/k3k.io_clustersets.yaml
  cli/cmds/cluster/create_flags.go
  docs/crds/crd-docs.md
  pkg/apis/k3k.io/v1alpha1/set_types.go
  pkg/apis/k3k.io/v1alpha1/types.go
  pkg/controller/cluster/server/server.go
  tests/cluster_test.go
Labels: documentation

#273 Update quickstart pre-requisite and add cli docs
  Makefile
  README.md
  cli/cmds/cluster.go
  cli/cmds/cluster_create.go
  cli/cmds/cluster_create_flags.go
  cli/cmds/cluster_delete.go
  cli/cmds/kubeconfig.go
  cli/cmds/root.go
  cli/main.go
  docs/advanced-usage.md
  docs/cli/cli-docs.md
  docs/cli/genclidoc.go
  docs/crds/Makefile
Labels: documentation

#301 Fix kubeconfig load from multiple configuration files
  cli/cmds/cluster_create.go
  cli/cmds/cluster_delete.go
  cli/cmds/kubeconfig.go
  cli/cmds/root.go
  docs/cli/cli-docs.md
Labels: bug

#314 Create dedicated namespace for new clusters
  Makefile
  cli/cmds/cluster.go
  cli/cmds/cluster_create.go
  cli/cmds/cluster_delete.go
  cli/cmds/kubeconfig.go
  cli/cmds/root.go
  go.mod
Labels: cli
